1) Loading data

```{r}
filePath = "E:\\Eskills-Academy-projects\\deepLearning-R-data\\Course-Data\\section1\\"
# setwd(filePath)    # Pointing R to look for data in this directory
```


# Read from local txt file
```{r}
txtFile = paste(filePath,'Resp2.txt', sep="")
resp2 = read.table(txtFile, header = TRUE,  sep = ',')
head(resp2)
```


# Read from local csv file
```{r}
csvFile = paste(filePath, "Resp1.csv", sep="")
resp1 <- read.csv(csvFile, header = TRUE)
head(resp1)
str(resp1)
summary(resp1)

csvFile2 = paste(filePath, "winequality-red.csv", sep="")
winer1 <- read.csv(csvFile2, header = TRUE, sep = ';')
head(winer1)
summary(winer1)
```


# Read from local excel file
```{r}
xlsFile = paste(filePath, 'boston1.xls', sep="")
library(readxl, help, pos = 2, lib.loc = NULL)
dfb <- read_excel(xlsFile)
head(dfb)
summaryDfb = summary(dfb)
```


# Using RCurl to read in csv data hosted online on github and other sites
```{r}
library(RCurl, help, pos = 2, lib.loc = NULL)
dataURL = getURL("https://raw.githubusercontent.com/sciruela/Happiness-Salaries/master/data.csv")

data1  <- read.csv(text=dataURL)
head(data1)
```


# Read table from a webpage
```{r}
library(XML)
tableURL = "https://en.wikipedia.org/wiki/2016_Summer_Olympics_medal_table"

UrlData = getURL(tableURL)
data = readHTMLTable(UrlData, stringAsFactors=FALSE)
# names(data)
# head(data)

x = data$`2016 Summer Olympics medal table`
head(x)
```